### ISSUE TITLE
Firefox doesn't show filter dialog

### ISSUE THREAD

**Issue by KyNorthstar** [Supuhstar/Rent-Split-Calculator#48]
The filter dialog isn't shown in Firefox because [HTMLDialogElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) is disabled by default.

See [Firefox bug #840640](https://bugzilla.mozilla.org/show_bug.cgi?id=840640)

**Comment by Rexogamer** [comment]
This can be enabled in `about:config` by setting `dom.dialog_element.enabled` to `true` - this will aslo be enabed by default in Firefox 98 (currently available on Nightly).

**Comment by KyNorthstar** [comment]
Thanks for the heads-up, @Rexogamer !

I've got big plans for a rewrite so hopefully I won't need this fixed anytime soon

**Comment by KyNorthstar** [comment]
Seems the default configuration of Firefox has this enabled now! Thank goodness
